"""
Reporter — generates a concise 1-page Markdown brief from scored advisories.
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import List

from .scorer import score_label

logger = logging.getLogger(__name__)

MAX_TOP_ITEMS = 10      # items in the Top Threats table
MAX_SUMMARY_ITEMS = 5   # items with full description block


def generate_brief(advisories: List[dict], output_path: Path, timestamp: str) -> None:
    """Render a 1-page threat intelligence brief in Markdown."""

    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    total = len(advisories)
    kev_count = sum(1 for a in advisories if a.get("in_kev"))
    critical_count = sum(1 for a in advisories if a.get("score", 0) >= 8.0)
    high_count = sum(1 for a in advisories if 6.0 <= a.get("score", 0) < 8.0)
    sources = sorted(set(a.get("source", "") for a in advisories))

    # Tag frequency
    tag_freq: dict[str, int] = {}
    for a in advisories:
        for t in a.get("tags", []):
            tag_freq[t] = tag_freq.get(t, 0) + 1
    top_tags = sorted(tag_freq.items(), key=lambda x: x[1], reverse=True)[:8]

    top_advisories = advisories[:MAX_TOP_ITEMS]
    summary_advisories = advisories[:MAX_SUMMARY_ITEMS]

    lines = [
        f"# Threat Intelligence Brief",
        f"**Generated:** {now}  |  **Pipeline run:** `{timestamp}`",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total advisories ingested | **{total}** |",
        f"| Sources | {', '.join(sources)} |",
        f"| Confirmed exploited (KEV) | **{kev_count}** |",
        f"| Critical priority (score ≥ 8.0) | **{critical_count}** |",
        f"| High priority (score 6.0–7.9) | **{high_count}** |",
        "",
    ]

    if top_tags:
        tag_str = "  ".join(f"`{t}` ×{c}" for t, c in top_tags)
        lines += [
            f"**Top vulnerability categories:** {tag_str}",
            "",
        ]

    lines += [
        "---",
        "",
        f"## Top {len(top_advisories)} Priority Threats",
        "",
        "| # | ID | Title | Source | Score | Priority | KEV |",
        "|---|-----|-------|--------|-------|----------|-----|",
    ]

    for i, a in enumerate(top_advisories, 1):
        score = a.get("score", 0)
        label = score_label(score)
        kev_flag = "✅" if a.get("in_kev") else "—"
        adv_id = a.get("id", "—")
        title = a.get("title", "—")[:60] + ("…" if len(a.get("title", "")) > 60 else "")
        source = a.get("source", "—")
        lines.append(f"| {i} | `{adv_id}` | {title} | {source} | **{score}** | {label} | {kev_flag} |")

    lines += ["", "---", "", f"## Detailed Advisories (Top {len(summary_advisories)})", ""]

    for a in summary_advisories:
        score = a.get("score", 0)
        label = score_label(score)
        cves = ", ".join(a.get("cve_ids", [])) or "N/A"
        tags = ", ".join(a.get("tags", [])) or "none"
        kev = "Yes — active exploitation confirmed" if a.get("in_kev") else "No"
        due = a.get("due_date") or "N/A"
        url = a.get("url") or ""

        lines += [
            f"### {a.get('title', 'Untitled')}",
            "",
            f"| Field | Value |",
            f"|-------|-------|",
            f"| **ID** | `{a.get('id', '—')}` |",
            f"| **Source** | {a.get('source', '—')} |",
            f"| **Priority Score** | **{score}** / 10.0 — {label} |",
            f"| **Severity** | {a.get('severity', '—')} |",
            f"| **CVSS** | {a.get('cvss_score', 'N/A')} |",
            f"| **CVEs** | {cves} |",
            f"| **In KEV** | {kev} |",
            f"| **CISA Due Date** | {due} |",
            f"| **Vendor/Product** | {a.get('vendor_project', '—')} / {a.get('product', '—')} |",
            f"| **Tags** | {tags} |",
            f"| **Published** | {a.get('published_date', '—')} |",
        ]

        if url:
            lines.append(f"| **Reference** | {url} |")

        desc = a.get("description", "").strip()
        if desc:
            lines += ["", f"> {desc[:400]}{'…' if len(desc) > 400 else ''}", ""]
        else:
            lines.append("")

    lines += [
        "---",
        "",
        "*This report was auto-generated by the Threat Intelligence Pipeline. "
        "All scores are computed algorithmically and should be validated by a security analyst.*",
    ]

    output_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info(f"Brief written to {output_path} ({len(lines)} lines)")
